Update apt package index in GH Action CI
The GH Action CI build is currently failing with the following error:

    E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/p/poppler/libpoppler-glib8_22.02.0-2ubuntu0.2_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    Error: Process completed with exit code 100.