Fix TypeError on "click->player#play" action
I was seeing the following JS exception in my browser in development:

    Error invoking action "click->player#play"
    TypeError: this.trackTargets[this.currentIndex()] is undefined

It seems as if the `showTrackTitle` function was being called when
`this.currentIndex()` was `-1`. I think we can safely ignore these calls
and so I've added a guard condition to the function.